apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    name: mysql
    app: phonebook-app
spec:
  selector:
    name: mysql # deployment'da template:metadata:labels:name:mysql ile aynı omalı
  type: ClusterIP
  ports:
    - name: db
      port: 3306
      targetPort: 3306
