apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  # namespace: phonebook-namespace  # namespace'i oluşturmak için sadece burayı eklerim.
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql
  template:
    metadata:
      labels:
        name: mysql # yukarıdaki selector:matchLabels:name: mysql ile aynı olmalı
        app: phonebook-app
    spec:
      containers:
      - name: phonebook
        image: mysql:5.7 
        ports:
          - containerPort: 3306  # mysql'in portu
        envFrom:
          - configMapRef:
              name: database-configmap
          - secretRef:
              name: mysql-secret
        volumeMounts:
          - name: mysql-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: db-pv-claim # pvclaim name ile aynı olmalı

