apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-claim  # deployment'da claimName'a yazılacak aynı olmalı
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual  # pv bu isimden buraya bağlanacak
  resources:
    requests:
      storage: 5Gi
