apiVersion: v1
kind: Service
metadata:
  name: result-server-service
  labels:
    name: result-server
    app: phonebook-app
spec:
  selector:
    name: result-server # deployment'da template:metadata:labels:name:result_server ile aynı omalı
  type: NodePort
  ports:
   - name: result-http
     port: 80     
     targetPort: 80
     nodePort: 30002
     protocol: TCP
