apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-server-deploy
  # namespace: phonebook-namespace  # namespace'i oluşturmak için sadece burayı ekledim.
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result-server
  template:
    metadata:
      labels:
        name: result-server # yukarıdaki selector:matchLabels:name: result_server ile aynı olmalı
        app: phonebook-app
    spec:
      containers:
      - name: result-server-pod
        image: alparslanu6347/result-server_flask-app:1.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80  # flask'in portu
        envFrom:
          - configMapRef:
              name: servers-configmap
          - secretRef:
              name: mysql-secret
        # resources:
        #   limits:
        #     memory: 600Mi
        #     cpu: 100m
        #   requests:
        #     memory: 300Mi
        #     cpu: 80m